version: "3.7"

services:
  registry_frontend:
    restart: always
    image: konradkleine/docker-registry-frontend:v2
    links:
      - registry:registry
    ports:
      - 5001:80
    environment:
      # Docker registry connection
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
      # The front-end is no SSL protected
      ENV_USE_SSL:
      # The registry is no SSL protected as well
      ENV_DOCKER_REGISTRY_USE_SSL: 
    networks:
      - internal

  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      # Native basic authenticate
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      # Specified http address
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - ./mnt:/var/lib/registry
      - ./auth:/auth
    networks:
      - internal
    tty: true

networks:
  internal:
    name: internal
    driver: bridge
