version: "3.7"

services:
  registry_frontend:
    restart: always
    image: konradkleine/docker-registry-frontend:v2
    links:
      - registry:registry
    ports:
      - 8443:443
    volumes:
      - ./certs/domain.crt:/etc/apache2/server.crt
      - ./certs/domain.key:/etc/apache2/server.key
    environment:
      # Docker registry connection
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
      # The front-end is SSL protected
      ENV_USE_SSL: 1
      # The registry is SSL protected as well
      ENV_DOCKER_REGISTRY_USE_SSL: 1
    networks:
      - internal

  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      # Native basic authenticate
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      # Register TLS certificate
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - ./mnt:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth
    networks:
      - internal
    tty: true

networks:
  internal:
    name: internal
    driver: bridge
